# Generated by Django 3.1.2 on 2020-12-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
