# Generated by Django 3.1.2 on 2021-01-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstat',
            name='symbol',
            field=models.CharField(max_length=255),
        ),
    ]
