# Generated by Django 3.1.2 on 2021-01-14 07:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='eps_growth',
            new_name='eps_growth_q',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='net_income_growth',
            new_name='eps_growth_y',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='is_accelerated',
            new_name='is_accelerated_q',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='is_eps_growth',
            new_name='is_accelerated_y',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='is_scrapper_succeeded',
            new_name='is_eps_growth_q',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sales_growth',
            new_name='net_income_growth_q',
        ),
        migrations.AddField(
            model_name='stock',
            name='is_eps_growth_y',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_scrapper_succeeded_q',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_scrapper_succeeded_y',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='net_income_growth_y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='stock',
            name='sales_growth_q',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='stock',
            name='sales_growth_y',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=None, null=True, size=None),
        ),
    ]
