# Generated by Django 3.1.2 on 2020-12-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_stock_in_watchlist',
            field=models.BooleanField(null=True),
        ),
    ]
