# Generated by Django 3.1.2 on 2020-10-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_technically_updated',
            field=models.DateTimeField(null=True, verbose_name='Last updated by the technical validation script'),
        ),
    ]
