# Generated by Django 3.1.2 on 2021-03-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0002_auto_20210320_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='gross_margins',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
