# Generated by Django 3.1.2 on 2021-01-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0002_auto_20210124_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksfilter',
            old_name='net_income_growth',
            new_name='eps_acceleration',
        ),
        migrations.RemoveField(
            model_name='stocksfilter',
            name='sales_growth',
        ),
    ]
