# Generated by Django 3.1.2 on 2020-12-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0002_stock_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_stat',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Da'),
        ),
        migrations.AddField(
            model_name='stock_stat',
            name='enter_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stock_stat',
            name='success_rate_10_4',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stock_stat',
            name='success_rate_15_6',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stock_stat',
            name='success_rate_18_7',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='stock_stat',
            name='success_rate_20_8',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
