# Generated by Django 3.1.2 on 2021-01-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0003_auto_20210124_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockstat',
            options={'ordering': ['symbol']},
        ),
    ]
