# Generated by Django 3.1.2 on 2021-01-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0004_auto_20210124_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksfilter',
            old_name='eps_acceleration',
            new_name='acceleration',
        ),
    ]
