# Generated by Django 3.1.2 on 2020-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0004_auto_20201009_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pivot',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
