# Generated by Django 3.1.2 on 2021-01-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0005_auto_20210124_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarterlystat',
            name='stockstat_ptr',
        ),
        migrations.DeleteModel(
            name='StocksFilter',
        ),
        migrations.RemoveField(
            model_name='yearlystat',
            name='stockstat_ptr',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quarterly_stats',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='yearly_stats',
        ),
        migrations.DeleteModel(
            name='QuarterlyStat',
        ),
        migrations.DeleteModel(
            name='StockStat',
        ),
        migrations.DeleteModel(
            name='YearlyStat',
        ),
    ]
