# Generated by Django 3.1.2 on 2020-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0005_auto_20201009_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_technically_updated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last technical update'),
        ),
    ]
