# Generated by Django 3.1.2 on 2020-12-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0005_auto_20201224_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_stat',
            name='yahoo_date_format',
            field=models.CharField(max_length=255),
        ),
    ]
