# Generated by Django 3.1.2 on 2021-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0006_auto_20210125_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price_to_sell',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
