# Generated by Django 3.1.2 on 2021-01-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0007_stock_price_to_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price_to_sell',
            new_name='price_to_sell_ratio',
        ),
    ]
