# Generated by Django 3.1.2 on 2020-10-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0008_auto_20201009_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_updated',
            field=models.DateField(verbose_name='Last scrapper1 update'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_technically_updated',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Last technical1 update'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
