# Generated by Django 3.1.2 on 2020-10-13 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0009_auto_20201012_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_scrapper_succeeded',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_updated',
            field=models.DateField(default=datetime.date(2020, 10, 13), verbose_name='Last scrapper1 update'),
        ),
    ]
