# Generated by Django 3.1.2 on 2020-10-13 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0012_auto_20201013_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_updated',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 9, 10, 39, 138839, tzinfo=utc), verbose_name='Last scrapper update'),
        ),
    ]
