# Generated by Django 3.1.2 on 2020-10-13 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0016_auto_20201013_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_updated',
            field=models.DateField(default=datetime.date(2020, 10, 13), verbose_name='Last scrapper update'),
        ),
    ]
