# Generated by Django 3.1.2 on 2020-10-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0018_auto_20201013_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='last_scrapper_updated',
            new_name='last_scrapper_update',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='last_technically_updated',
            new_name='last_technically_update',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_rater_updated',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Last rater1 update'),
        ),
    ]
