# Generated by Django 3.1.2 on 2020-10-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0019_auto_20201013_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='last_rater_updated',
            new_name='last_rater_update',
        ),
    ]
