# Generated by Django 3.1.2 on 2020-10-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0020_auto_20201013_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='last_technically_update',
            new_name='last_technically_valid_update',
        ),
    ]
