# Generated by Django 3.1.2 on 2020-10-13 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0021_auto_20201013_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=datetime.date(2020, 10, 14), verbose_name='Last scrapper update'),
        ),
    ]
