# Generated by Django 3.1.2 on 2020-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0022_auto_20201014_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_in_breakout',
            field=models.BooleanField(null=True),
        ),
    ]
