# Generated by Django 3.1.2 on 2020-10-15 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0023_stock_is_in_breakout'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_breakout',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Last breakout1'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=datetime.date(2020, 10, 15), verbose_name='Last scrapper1 update'),
        ),
    ]
