# Generated by Django 3.1.2 on 2020-10-16 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0024_auto_20201015_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=datetime.date(2020, 10, 16), verbose_name='Last scrapper1 update'),
        ),
    ]
