# Generated by Django 3.1.2 on 2020-10-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0025_auto_20201016_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_in_breakout',
        ),
    ]
