# Generated by Django 3.1.2 on 2020-10-17 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0026_remove_stock_is_in_breakout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=datetime.date(2020, 10, 17), verbose_name='Last scrapper update'),
        ),
    ]
