# Generated by Django 3.1.2 on 2020-10-24 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0027_auto_20201017_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=datetime.date(2020, 10, 24), verbose_name='Last scrapper update'),
        ),
    ]
