# Generated by Django 3.1.2 on 2020-10-21 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0028_auto_20201020_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=datetime.date(2020, 10, 21), verbose_name='Last scrapper update'),
        ),
    ]
