# Generated by Django 3.1.2 on 2020-11-06 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0029_auto_20201106_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last scrapper update'),
        ),
    ]
