# Generated by Django 3.1.2 on 2020-11-06 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0030_auto_20201106_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=datetime.datetime(2020, 11, 6, 12, 27, 23, 419851), verbose_name='Last scrapper update'),
        ),
    ]
