# Generated by Django 3.1.2 on 2020-11-06 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0031_auto_20201106_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateField(default=datetime.date(2020, 11, 6), verbose_name='Last scrapper update'),
        ),
    ]
