# Generated by Django 3.1.2 on 2020-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0032_auto_20201106_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_breakout',
            field=models.BooleanField(null=True),
        ),
    ]
