# Generated by Django 3.1.2 on 2020-11-06 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0033_stock_is_breakout'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_scrapper_update1',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 17, 38, 10, 403443, tzinfo=utc), verbose_name='Last scrapper update (try'),
        ),
    ]
