# Generated by Django 3.1.2 on 2020-11-06 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0034_stock_last_scrapper_update1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last scrapper update (try'),
        ),
    ]
