# Generated by Django 3.1.2 on 2020-11-06 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0035_auto_20201106_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update1',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 17, 45, 59, 510160, tzinfo=utc), verbose_name='Last scrapper update (try'),
        ),
    ]
