# Generated by Django 3.1.2 on 2020-11-06 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0036_auto_20201106_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_scrapper_update2',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last scrapper update 2'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last scrapper update 1'),
        ),
    ]
