# Generated by Django 3.1.2 on 2020-11-07 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0037_auto_20201106_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_scrapper_update1',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_scrapper_update2',
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last scrapper update'),
        ),
    ]
