# Generated by Django 3.1.2 on 2020-11-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0038_auto_20201107_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_breakout',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last breakout'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_rater_update',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last rater update'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_scrapper_update',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last scrapper update'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_technically_valid_update',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last technical update'),
        ),
    ]
