# Generated by Django 3.1.2 on 2020-10-09 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_tracker', '0006_auto_20201009_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='net_income_growth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
